-- Optional: Disable RLS for all tables
-- Run this AFTER schema is created via drizzle-kit push:pg

-- Auth-related tables
ALTER TABLE IF EXISTS "user" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "account" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "session" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "verificationToken" DISABLE ROW LEVEL SECURITY;

-- Application tables
ALTER TABLE IF EXISTS addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cart_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wishlists DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS brands DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS banners DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS testimonials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS hero_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS refund_requests DISABLE ROW LEVEL SECURITY;

-- Verify RLS status
SELECT schemaname, tablename, rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY tablename;
